travis:
  secure:
    BINSTAR_TOKEN: WdN8gTauItOHweFJ+PpjdI/omS432tTfLTTzexPZHpjuvpPYWY8I1EKTtWOkuTTT1FB45UrWO5Iskntjv1/FpYGjsVx4et3RoCxK4q+EQyVQcAxekN07xU/li6Vc25m9n4BBUM8a0BbU/jk+4d74hY2JjaL7IM9CGzePgNJ/aAe4vn4wDhwnN+MMgcxIdqPLofYpcpKMWShfyajFgd45+PTWW8YBr2nvnmqAvlFH6a4lAutRtBYRGdavO5+VbHDEAYmrsFBkM81TTdxpw+xfBI3Vg2UeSpzd7Bv+JtstpYXYjz93eWH5+0RGPpv/T/NaxrOGcYA7P+ZmSdWAGVpzYQUavKoTDX7L6hkGkFyy9VF8aRF9ZLLgviCX0tPwlLFi17s7wX4EdAgQ6EbqeCd3+jWLo0mbne+jYUd3K7Xo8yMmu6U37RbA4oY5oGK9vvVTiWOGFz9DWyQlDJ1e714P/CWuAjLpo6Cv7UuCDkRJOQnTU1Pay0z1ainYjWCYWodswoPw91PFOttfa1mmcgamKDgXr9TPbtjxxxvfDAttGr/uSPfOco9/00gZKooIoJtPUaQpnEeVYgnylc2LBcRMedjfVN0notHSkfjj+McsBy92gfagDeiorfMkVbwFTTD7PBinwb1czPgRav53Mq6Fc5iaXDKJJVXEV7nYGCzEsCI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
